services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ghcr.io/evrone/bmstu_2024_dev
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle:cached
    ports:
      - 3000:3000
      - 12345:12345
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  bundle:
