services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - .:/rails
    ports:
      - 3000:3000
      - 12345:12345
    depends_on:
      - postgres
    healthcheck:
      test: curl --fail http://localhost:3000/up || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - redis:/data

volumes:
  postgres-data:
  redis:
