Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
