name: "CI"
on:
  pull_request:
    branches: [ "dev", "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1

      - name: Prepare
        run: cp ./.env.example ./.env  

      - name: Setup container
        run: make setup

      - name: Lint code
        run: make rubocop
