name: "CI"
on:
  pull_request:
    branches: [ "dev", "main" ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.2.0'

      - name: Prepare
        run: cp ./.env.example ./.env

      - name: Build container
        run: make ci-build

      - name: Lint code
        run: make ci-rubocop
