name: "CI"
on:
  pull_request:
    branches: [ "dev", "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup container
        run: make setup

      - name: Lint code
        run: make rubocop
